### ISSUE TITLE
言語選択 Reactが実質機能していない

### ISSUE THREAD

**Issue by 6sRyuSK** [mikkame/lets-contribute#30]
**バグの詳細**
よくわからないissue達が取得される。
そもそもgithubがReactを認識してくれないみたいです😓
https://github.com/search?q=language%3AReact

**改善案**
topicを用いる。
issue検索のクエリでtopicを指定できないみたいなので、
一度`topic:react`でリポジトリを検索してヒットしたリポジトリからissueを取得してくる
https://github.com/search?q=topic%3Areact+good-first-issues%3A%3E1

一応リポジトリは取得できるみたいですが日本語のリポジトリかどうか判断するのはちょっと難しそうです。

もしくはJavaScript or TypeScriptでissue検索したうえで
そのリポジトリにreactのトピックが設定されているかを確認して取得する方法がいいかもです！

**Comment by mikkame** [comment]
vueを追加したからreatもって思ったのですが・・・
ひょっとしたjsxなら行けるかな？

**Comment by mikkame** [comment]
jsx=reactという浅はかな考え・・・

**Comment by reta-ygs** [comment]
これがlanguageで指定できる言語一覧ですかね？
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

**Comment by mikkame** [comment]
ReactからJSXに変更すればいいかな・・・？
それか一旦消して緩募していく

**Comment by 6sRyuSK** [comment]
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L31
```
# group                 - Name of the parent language. Languages in a group are counted
#                         in the statistics as the parent language.
```
groupに入っている言語として扱われるそうです。
```
JSX:
  type: programming
  group: JavaScript
  extensions:
  - ".jsx"
  tm_scope: source.js.jsx
  ace_mode: javascript
  codemirror_mode: jsx
  codemirror_mime_type: text/jsx
  language_id: 178
```
なのでJSXはJavaScriptとしてカウントされる。
クエリでlanguage:JSXという風に検索することもできないっぽいです、、、
